<?xml version="1.0"?>
<package format="3">
  <name>pladypos</name>
  <version>1.0.0</version>
  <description>ROS2 package for the control, state estimation, and simulation of the PlaDyPos Unmanned Surface Vehicle (USV). Originally designed and developed by LABUST members and updated by the German Research Center for Artificial Intelligence (DFKI).</description>
  <maintainer email="bsaldarriaga@inaut.unsj.edu.ar">Brayan Saldarriaga</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>urdf</depend>
  <depend>xacro</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
